#pragma once

typedef enum {
    NONE,
    AMARELO,
    VERDE,
    VERMELHO
} Cor;

typedef enum {
    FALSE,
    TRUE
} Bool;

typedef enum {
    OK,
    ERRO_ALOCACAO_MEMORIA,
    ERRO_ABERTURA_ARQUIVO,
    ERRO_OVERFLOW_PALAVRA,
    ERRO_TAMANHO_BUFFER,
    ERRO_TECLAS_TECLADO,
    ERRO_INDICE_FORA_DE_ALCANCE,
    ERRO_TAMANHO_PALAVRA,
    ERRO_CARACTER_INVALIDO,
    ERRO_PALAVRA_REPETIDA,
    ERRO_CHAMADA_INVALIDA,
    ERRO_ARQUIVO_VAZIO,
} Status;
